---
- name: Deploy NiFi and ZooKeeper clusters
  hosts: nifi_cluster,zookeeper_cluster
  become: true

  vars:
    nifi_version: "1.15.3"  # default NiFi version
    zookeeper_version: "3.7.1"  # default ZooKeeper version
    lpda_enabled: false  # default LPAD enabled
    ssl_enabled: false  # default SSL enabled
    python_version: "3.10"  # default Python version

  tasks:
  - name: Install Docker
    package:
      name: docker
      state: present

  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Pull NiFi Docker image
    docker_image:
      name: apache/nifi:{{ nifi_version }}
      source: pull
    when: "'nifi_cluster' in group_names"

  - name: Pull ZooKeeper Docker image
    docker_image:
      name: zookeeper:{{ zookeeper_version }}
      source: pull
    when: "'zookeeper_cluster' in group_names"

  - name: Create NiFi containers
    docker_container:
      name: nifi-{{ inventory_hostname }}
      image: apache/nifi:{{ nifi_version }}
      ports:
        - "8080:8080"
      volumes:
        - /opt/nifi/conf:/opt/nifi/conf
      environment:
        NIFI_WEB_HTTP_PORT: 8080
        NIFI_WEB_HTTPS_PORT: 8443
        NIFI_LPAD_ENABLED: "{{ lpda_enabled | bool }}"
        NIFI_SSL_ENABLED: "{{ ssl_enabled | bool }}"
    when: "'nifi_cluster' in group_names"

  - name: Create ZooKeeper containers
    docker_container:
      name: zookeeper-{{ inventory_hostname }}
      image: zookeeper:{{ zookeeper_version }}
      ports:
        - "2181:2181"
      volumes:
        - /opt/zookeeper/conf:/opt/zookeeper/conf
    when: "'zookeeper_cluster' in group_names"

  - name: Install Python 3.10
    package:
      name: python3.10
      state: present

  - name: Configure NiFi cluster
    template:
      src: templates/nifi.properties.j2
      dest: /opt/nifi/conf/nifi.properties
      mode: '0644'
    notify: restart nifi
    when: "'nifi_cluster' in group_names"

  - name: Configure ZooKeeper cluster
    template:
      src: templates/zookeeper.properties.j2
      dest: /opt/zookeeper/conf/zookeeper.properties
      mode: '0644'
    notify: restart zookeeper
    when: "'zookeeper_cluster' in group_names"

  handlers:
  - name: restart nifi
    docker_container:
      name: nifi-{{ inventory_hostname }}
      state: restarted
    when: "'nifi_cluster' in group_names"

  - name: restart zookeeper
    docker_container:
      name: zookeeper-{{ inventory_hostname }}
      state: restarted
    when: "'zookeeper_cluster' in group_names"
